add_subdirectory(grammar)
add_subdirectory(lexer)
add_subdirectory(ast)
add_subdirectory(parser)
add_executable(jkbuf compiler/main.cpp)
add_executable(jk::jkbuf ALIAS jkbuf)
target_link_libraries(jkbuf PRIVATE ridl_parser)
target_compile_options(jkbuf PRIVATE -Wall -Wextra -Wpedantic)
install(TARGETS jkbuf EXPORT jk_nodeinfraTargets RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
