#!/bin/sh
# Shutdown: run /etc/init.d/S??* stop in reverse order, then unmount.

for s in $(ls -r /etc/init.d/S[0-9][0-9]* 2>/dev/null); do
    [ -x "$s" ] && "$s" stop
done

sync
umount -a -r 2>/dev/null
