include_guard(GLOBAL)

# build_jkbuf(NAME target MSG_FILES file.jkbuf ... [INCLUDE_DIRS dir ...])
# Generated headers preserve paths relative to this source directory under
# <current binary directory>/<target>/, which is exported as an include path.
function(build_jkbuf)
  if(CMAKE_VERSION VERSION_LESS 3.20)
    message(FATAL_ERROR "build_jkbuf requires CMake 3.20 or newer")
  endif()
  cmake_parse_arguments(PARSE_ARGV 0 JK "" "NAME" "MSG_FILES;INCLUDE_DIRS")
  if(JK_UNPARSED_ARGUMENTS OR JK_KEYWORDS_MISSING_VALUES OR NOT JK_NAME OR NOT JK_MSG_FILES)
    message(FATAL_ERROR "Usage: build_jkbuf(NAME target MSG_FILES file.jkbuf ... [INCLUDE_DIRS dir ...])")
  endif()
  if(TARGET "${JK_NAME}" OR TARGET "${JK_NAME}_generate")
    message(FATAL_ERROR "build_jkbuf: target ${JK_NAME} already exists")
  endif()
  if(NOT TARGET jk::jk_message_headers)
    message(FATAL_ERROR "build_jkbuf requires find_package(jk_nodeinfra CONFIG REQUIRED) or add_subdirectory(nodeinfra) first")
  endif()

  if(JKBUF_HOST_EXECUTABLE)
    if(NOT IS_ABSOLUTE "${JKBUF_HOST_EXECUTABLE}" OR NOT EXISTS "${JKBUF_HOST_EXECUTABLE}")
      message(FATAL_ERROR "JKBUF_HOST_EXECUTABLE must be an existing absolute path to a native jkbuf")
    endif()
    set(compiler "${JKBUF_HOST_EXECUTABLE}")
    set(compiler_dependency "${JKBUF_HOST_EXECUTABLE}")
  elseif(CMAKE_CROSSCOMPILING)
    message(FATAL_ERROR "Cross builds require -DJKBUF_HOST_EXECUTABLE=/path/to/native/jkbuf")
  elseif(TARGET jk::jkbuf)
    set(compiler "$<TARGET_FILE:jk::jkbuf>")
    set(compiler_dependency jk::jkbuf)
  else()
    message(FATAL_ERROR "build_jkbuf: jk::jkbuf compiler target is unavailable")
  endif()

  set(include_args)
  foreach(directory IN LISTS JK_INCLUDE_DIRS)
    get_filename_component(directory "${directory}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    list(APPEND include_args -I "${directory}")
  endforeach()
  set(output_root "${CMAKE_CURRENT_BINARY_DIR}/${JK_NAME}")
  set(headers)
  foreach(schema IN LISTS JK_MSG_FILES)
    get_filename_component(input "${schema}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    if(NOT EXISTS "${input}" OR IS_DIRECTORY "${input}")
      message(FATAL_ERROR "build_jkbuf: message file does not exist: ${input}")
    endif()
    file(RELATIVE_PATH relative "${CMAKE_CURRENT_SOURCE_DIR}" "${input}")
    if(relative MATCHES "^\\.\\./" OR IS_ABSOLUTE "${relative}")
      message(FATAL_ERROR "build_jkbuf: MSG_FILES must be inside ${CMAKE_CURRENT_SOURCE_DIR}; use INCLUDE_DIRS for shared schemas")
    endif()
    get_filename_component(extension "${relative}" LAST_EXT)
    if(NOT extension STREQUAL ".jkbuf" AND NOT extension STREQUAL ".ridl")
      message(FATAL_ERROR "build_jkbuf: expected a .jkbuf or .ridl file: ${schema}")
    endif()
    string(REGEX REPLACE "\\.(jkbuf|ridl)$" ".h" relative_header "${relative}")
    set(header "${output_root}/${relative_header}")
    if(header IN_LIST headers)
      message(FATAL_ERROR "build_jkbuf: duplicate generated header: ${header}")
    endif()
    get_filename_component(output_directory "${header}" DIRECTORY)
    add_custom_command(OUTPUT "${header}"
      COMMAND "${CMAKE_COMMAND}" -E make_directory "${output_directory}"
      COMMAND "${compiler}" ${include_args} --depfile "${header}.d" -o "${header}" "${input}"
      DEPENDS ${compiler_dependency} "${input}"
      DEPFILE "${header}.d"
      BYPRODUCTS "${header}.d"
      COMMENT "Generating jkbuf header ${relative_header}"
      VERBATIM)
    list(APPEND headers "${header}")
  endforeach()
  add_custom_target("${JK_NAME}_generate" DEPENDS ${headers})
  add_library("${JK_NAME}" INTERFACE)
  add_dependencies("${JK_NAME}" "${JK_NAME}_generate")
  target_include_directories("${JK_NAME}" INTERFACE "$<BUILD_INTERFACE:${output_root}>")
  target_link_libraries("${JK_NAME}" INTERFACE jk::jk_message_headers)
endfunction()
